# Generated by Django 4.2 on 2023-06-21 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_application_submitted_by_application_submitted_for_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="image",
        ),
        migrations.AddField(
            model_name="job",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="logo/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
