# Generated by Django 4.2 on 2023-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_remove_job_image_job_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("-----------", "Select One Type"),
                    ("teacher", "Teacher"),
                    ("IT", "IT"),
                    ("computerprogrammer", "Computer Programmer"),
                    ("graphicsdesigner", "Graphics Designer"),
                    ("webdeveloper", "Web Developer"),
                    ("databaseadministrator", "Database Administrator"),
                    ("technician", "Technician"),
                    ("accountant", "Accountant"),
                    ("softwaredeveloper", "Software Developer"),
                    ("webdesigner", "Web Designer"),
                    ("hardwareengineer", "Hardware Engineer"),
                    ("networkadministrator", "Network Administrator"),
                    ("hardwarearchitect", "Hardware Architect"),
                    ("dataanalyst", "Data Analyst"),
                    ("systemadministrator", "System Administrator"),
                    ("computerscientist", "Computer Scientist"),
                    ("softwareengineer", "Software Engineer"),
                    ("systemsecurity", "System Securtiy"),
                    ("mobileapplicationdeveloper", "Mobile Application Developer"),
                    ("gamedesigner", "Game Designer"),
                    ("gamedeveloper", "Game Developer"),
                    ("visualdeveloper", "Visual Developer"),
                    ("networkanalyst", "Network Analyst"),
                    ("networkmanager", "Network Manager"),
                    ("networkdesigner", "Network Designer"),
                    ("networkengineer", "Network Engineer"),
                    ("softwaretester", "Software Tester"),
                    ("datascientist", "Data Scientist"),
                    ("dataarchitect", "Data Architect"),
                    ("softwarearchitect", "Software Architect"),
                    ("informationarchitect", "Information Architect"),
                    ("statisticalprogrammer", "Statistical Programmer"),
                    ("itinstructor", "IT Instructor"),
                    ("textureartist", "Texture Artist"),
                    ("technicalartist", "Technical Artist"),
                    ("gamedirector", "Game Director"),
                    ("gameproducer", "Game Producer"),
                    ("animator", "Animator"),
                    ("animationsupervisor", "Animation Supervisor"),
                    ("itmanager", "IT Manager"),
                    ("webmaster", "Web Master"),
                    ("webeditor", "Web Editor"),
                    ("contentmanager", "Content Manager"),
                    ("cinematicartist", "Cinematic Artist"),
                    ("characterdesigner", "Character Designer"),
                    ("supervisor", "Supervisor"),
                    ("professionalgamer", "Profesional Gamer"),
                ],
                default="-----------",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("-----------", "Select One Category"),
                    ("freelancer", "Freelancer"),
                    ("parttime", "Parttime"),
                    ("fulltime", "Fulltime"),
                    ("intern", "Intern"),
                ],
                default="-----------",
            ),
        ),
    ]
