# Generated by Django 4.2 on 2023-07-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_message_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="employer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
