# Generated by Django 4.2 on 2023-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_job_level_alter_job_application_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="level",
            field=models.CharField(
                choices=[
                    ("-----------", "Select One Level"),
                    ("Entry", "Entry"),
                    ("Mid", "Mid"),
                    ("Senior", "Senior"),
                    ("Manager", "Manager"),
                ],
                default="-----------",
            ),
        ),
    ]
