# Generated by Django 4.2 on 2023-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_alter_job_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("-----------", "Select One Category"),
                    ("Free Lancer", "Free Lancer"),
                    ("Part Time", "Part Time"),
                    ("Full Time", "Full Time"),
                    ("Intern", "Intern"),
                    ("Temporary", "Temporary"),
                    ("Contract", "Contract"),
                ],
                default="-----------",
            ),
        ),
    ]
